server:
  port: 8000

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: 192.168.0.101
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

