server:
  port: 8100

spring:
  application:
    name: config-server
  # 注册中心配置，连接git获取配置文件
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lzw1017400172/LZW_DS-config.git
          search-paths: config
          username: lzw1017400172
          password: lzw8407853

#注册为eureka server为了实现配置中心的高可用
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.101:8000/eureka/


